### ISSUE TITLE
Any way of programatically creating only one ripple

### ISSUE THREAD

**Issue by fluxxus** [m-ender/webgl-ripples#1]
As the title says, is it possible to create only one ripple? 

Thanks

**Comment by m-ender** [comment]
The ripples are created with `addSplash` (see https://github.com/mbuettner/webgl-ripples/blob/master/waves.js#L326). This is currently used twice in `render`: Once [for random ripples](https://github.com/mbuettner/webgl-ripples/blob/master/waves.js#L403) and once [for clicks](https://github.com/mbuettner/webgl-ripples/blob/master/waves.js#L408). 

You will want to remove/comment out at least the first of these (or set `randomSplashP = 0`) and then add a new call with the position you want to render it at (and make sure that it's only called once by setting a global variable or similar, since `render` is run for every frame).
